### ISSUE TITLE
OutOfMemoryError during Calculation using API

### ISSUE THREAD

**Issue by slothyoung** [GreenDelta/openlca-python-tutorial#14]
I am currently working with the OpenLCA API in Eclipse. But with some Processes/Product Systems, I encounter an OutOfMemoryError during the Calculation of a ProductSystem.

The following is the Print-Stack:
Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space
    at org.apache.commons.math3.linear.Array2DRowRealMatrix.copyOut(Array2DRowRealMatrix.java:528)
    at org.apache.commons.math3.linear.Array2DRowRealMatrix.getData(Array2DRowRealMatrix.java:253)
    at org.apache.commons.math3.linear.LUDecomposition.<init>(LUDecomposition.java:92)
    at org.apache.commons.math3.linear.LUDecomposition.<init>(LUDecomposition.java:75)
    at org.openlca.core.matrix.solvers.JavaSolver.solve(JavaSolver.java:23)
    at org.openlca.core.math.LcaCalculator.calculateContributions(LcaCalculator.java:73)

The line causing the error is the following:
        ContributionResult result = calculator.calculateContributions(setup);

I was monitoring my RAM Usage (8GB Machine) and RAM was not required more than 80% shortly before the crash. I do not have this behavior with every calculation, but with many. In OpenLCA itself, the calculations finishes without problems.

The question I ask myself now is, how to remedy this Error?

**Comment by msrocka** [comment]
You can increase the heap space for your Python script in Eclipse under `Run > Run Configuration`. There you can set the max. heap space parameter for the JVM via the `-Xmx` flag, e.g. `-Xmx2048M` would set it to 2048 megabytes. See also [this answer  on Stackoverflow](https://stackoverflow.com/a/8601040/599575).

Also, you could use the native library and the `DenseSolver` for faster calculations (see [line 113](https://github.com/GreenDelta/openlca-python-tutorial/blob/master/example.py#L113) in the example script).

**Comment by slothyoung** [comment]
Thanks for the reply!

I am afraid to have not explained my case well enough. I am not trying to run Python Scripts inside OpenLCA, but rather use the APIs in Eclipse, basically following this tutorial:
https://github.com/GreenDelta/openlca-python-tutorial/blob/master/ide_setup.md

However, I do not use Jython, but Java directly. And in this situation, the Exceptions are thrown. I already raised the Maximum Heap Size, but that unfortunately did not help.
The DenseSolver did not work for me either because i get an UnsatisfiedLinkError. Maybe there is something that I am missing.
